---
title: "categorization"
author: "Marlon Schumacher"
date: "24 1 2019"
output: html_document
---

```{r}
library(pacman)
p_load(dplyr, haven, readr, ggplot2, pdftools, stringr, lubridate, RColorBrewer, tm, ggthemes, RTextTools,
       caret, randomForest, magrittr)

library(forcats)
```


```{r}
load("df_complete_clean.RData")

# removing numbers and punctuation
df_complete_clean$title %<>% 
  removeNumbers() %>% 
  removePunctuation()

# does work
head(grepl("polizei", df_complete_clean$title))

head(grepl(("polizei|sicherheit"), df_complete_clean$title))

df_complete_clean$title
  
head(df_complete_clean)

# deleting all files with no title (15 rows only)
df_complete_clean %<>% 
  filter(!is.na(title))

```

## matching with str_detect
```{r}
# matching words for each category

# topic 1
makroöko <- c("arbeitslosigkeit", "arbeitslosenquote", "zinsen","haushaltsschulden",
              "steuer","industrie") %>% 
  paste0(collapse = "|")

# topic 2
buerger <- c("diskriminierung", "minderheit", "meinungsfreiheit", "religionsfreiheit", 
             "partizipation", "wahlrecht", "gender", "gleichberechtigung", "gleichstellung",
             "gleichgeschlechtliche ehen", "öffentlichkeitsbeteiligung") %>% 
  paste0(collapse = "|")

# topic 3
gesundheit <- c("pflege", "pflegeversicherung", "krankenversicherung", "krankenkasse",
                "arzt", "krankheit","impfquote", "impfung", "alkoholkonsum", "arzneimittel",
                "gesundheitsschutz", "medizin", "patienten") %>% 
  paste0(collapse = "|")

# topic 4
agrar <- c("agrar", "landwirtschaft", "landwirte", "pflanzenschutzmittel","glyphosat") %>% 
  paste0(collapse = "|")

# topic 5
arbeit <- c("gewerkschaft", "elternzeit", "kinderbetreuung", "saisonarbeit", "arbeitsschutz", 
            "arbeitssicherheit", "mindestlohn", "mindestlöhne", "streik", "überstunden",
            "arbeitszeitgesetz", "fachkräftemangel", "arbeitszeit", "geringfügige beschäftigung",
            "befristete beschäftigung", "arbeitsbedingungen", "befristeter beschäftigung",
            "leiharbeit", "arbeit auf abruf", "arbeitsunfälle", "stellenabbau",
            "niedriglöhne") %>% 
  paste0(collapse = "|")

# topic 6
bildung <- c("studium", "lehrer", "schule", "universität", "weiterbildung",
             "geisteswissenschaften", "hochschul") %>% 
  paste0(collapse = "|")

# topic 7 
umwelt <- c("trinkwasser", "recycling", "müll", "luftverschmutzung", "plastik",
            "klimawandel", "emission", "artenschutz", "stickoxide", "wasserqualität", "umwelt",
            "klimaschutz", "insekten", "co2-speicherung", "grundwasser", "tierschutz",
            "atomtransport", "ökologisch") %>% 
  paste0(collapse = "|")

# topic 8
energie <- c("kohle", "kohleausstieg", "energie", "atomkraft", "solar", "windenergie", "erneuerbare",
             "atomstandort") %>% 
  paste0(collapse = "|")

# topic 9
einwanderung <- c("flüchtlinge", "asyl", "migration", "einwanderer", "einwanderung", 
                  "abschiebung", "integration", "familiennachzug", "schutzsuchende",
                  "fluchtursachen", "duldung", "zuwanderung") %>% 
  paste0(collapse = "|")

# topic 10
transport <- c("autobahn", "schienenverkehr", "bahn", "flughafen", "lkw", "maut", "mobilität", 
               "schienen", "zugverspätung", "verkehrswende", "verkehrsprojekt", "radverkehr",
               "verkehrspolitik", "straßenbrücke", "verkehrsminister") %>% 
  paste0(collapse = "|")

# topic 11
krimi <- c("rauschmittel", "steuerhinterziehung", "bnd", "bundesnachrichtendienst", 
           "gefängnis", "kindesmissbrauch", "kinderpornografie", "interpol", 
           "kindesentführung", "straftaten", "kriminalität", "sicherungsverwahrung",
           "tötungsdelikte", "haftbefehl", "bundeskriminalamt", "polizei", "gewalttaten",
           "linksextrem", "rechtsextrem", "ermittlungsverfahren", "gefährder") %>% 
  paste0(collapse = "|")

# topic 12
sozi <- c("arbeitslosengeld", "renten", "altersarmut", "pension", "armut", "tafel", "kindergeld",
          "jobcenter", "sgb-ii", " rente ", "vermögensungleichheit", "einkommensungleichheit",
          "riester-rente", "sozialgesetzbuch", "altersvorsorge") %>% 
  paste0(collapse = "|")

# topic 13
wohn <- c("mietpreis", "miete", "wohnung", "obdachlos", "wohnhilfe", "wohnheim",
          "brachfläche", "wohnen") %>% 
  paste0(collapse = "|")

# topic 14
banken <- c("bank", "kartell", "finanzsektor", "verbraucherschutz", "tourismus", "patent", "urheberrecht",
            "verbraucherschutz", "verbraucherrecht", "fluthilfe", "wettbewerbsbeschränkung", "katastrophenschutz",
            "finanzmarkt", "kapitalmarkt") %>% 
  paste0(collapse = "|")

# topic 15
verteidigung <- c("bundeswehr", "kriegseinsatz", "kriegseinsätze", "nato") %>% 
  paste0(collapse = "|")

# topic 16
tech_kom <- c("internet", "breitband", "telekommunikation", "gez", "rundfunk", "twitter", "facebook",
              "digitalisierung", "raumfahrt", "cybersicherheit") %>% 
  paste0(collapse = "|")

# topic 17
außenh <- c("handelsabkommen", "export", "import", "zölle", "einfuhrbeschränkung", 
            "einfuhr", "steueroasen", "freihandel", "außenhandel", "export", "waffenexport",
            "ceta", "ttip", "transatlantic trade") %>% 
  paste0(collapse = "|")

# topic 18
int_aus <- c("auslandshilfe", "entwicklungsländer", "menschenrecht", "humanitäre hilfe", "brexit",
             "arbeitsbedingungen in schwellen und entwicklu", "islamischer staat", "terror",
             "bürgerkrieg") %>% 
  paste0(collapse = "|")

regierung <- c(" sanktionen ", "bürokratieentlastung", "bürokratieabbau", 
               "bundesanstalt für immobilienaufgaben", "deutsch-georgische", "deutsch-türkischen",
               "deutsch-indischen", "deutsch-montenegrinische", "deutsch-russische",
               "deutsch-armenische", "deutsch-ukrainische", "deutschland und aserbaidschan",
               "diplomat") %>% 
  paste0(collapse = "|")

# public goods muss raus, da es hierzu nahezu keinerlei Themen gibt
public_goods <- c("denkmal", "denkmäler") %>% 
  paste0(collapse = "|")

library(magrittr)
df_complete_clean %<>% 
  mutate(thema = case_when(
    str_detect(title, makroöko) ~ "Makroökonomie", #1
    str_detect(title, buerger) ~ "Bürgerrechte",#2
    str_detect(title, gesundheit) ~ "Gesundheit", #3
    str_detect(title, agrar) ~ "Agrarwirtschaft", #4
    str_detect(title, arbeit) ~ "Arbeit & Beschäftigung", #5
    str_detect(title, bildung) ~ "Bildung", #6
    str_detect(title, umwelt) ~ "Umwelt", #7
    str_detect(title, energie) ~ "Energie", #8
    str_detect(title, einwanderung) ~ "Einwanderung", #9
    str_detect(title, transport) ~ "Transport", #10
    str_detect(title, krimi) ~ "Kriminalität & Familienprobleme", #11
    str_detect(title, sozi) ~ "Soziale Wohlfahrt", #12
    str_detect(title, wohn) ~ "Gemeindeentwicklung & Wohnungsprobleme", #13
    str_detect(title, banken) ~ "Banken, Finanzen & Binnenhandel", #14
    str_detect(title, verteidigung) ~ "Verteidigung", #15
    str_detect(title, tech_kom) ~ "Technologie & Kommunikation", #16
    str_detect(title, außenh) ~ "Außenhandel", #17
    str_detect(title, int_aus) ~ "Internationale Angelegenheiten & Auslandshilfe", #18
    str_detect(title, regierung) ~ "Regierungsoperationen", #19
    # str_detect(title, public_goods) ~ "Öffentliche Flächen", #20
    TRUE ~ "zSonstiges"
  ))

df_complete_clean %>% 
  sjmisc::frq(thema) %>% 
  kableExtra::kable()

df_complete_clean %>% 
  filter(str_detect(title, "diplomat") == TRUE)


View(df_complete_clean %>% 
       select(title, thema, file) %>% 
       filter(thema == "zSonstiges"))
```

## checking categories if the fitting is good
```{r}
# looks very good
View(df_complete_clean %>% 
  select(title, thema) %>% 
  filter(thema == "Soziale Wohlfahrt"))

View(df_complete_clean %>% 
  select(title, thema) %>% 
  filter(thema == "Gemeindeentwicklung & Wohnungsprobleme"))

View(df_complete_clean %>% 
  select(title, thema) %>% 
  filter(thema == "Transport"))
```

## checking overlapping
```{r}
df_overlap <- df_complete_clean %>% 
  mutate(makroökonomie = case_when(str_detect(title, makroöko) ~ 1, TRUE ~ 0)) %>% 
  mutate(buerger = case_when(str_detect(title, buerger) ~ 1, TRUE ~ 0)) %>% 
  mutate(gesundheit = case_when(str_detect(title, gesundheit) ~ 1, TRUE ~ 0)) %>% 
  mutate(agrar = case_when(str_detect(title, agrar) ~ 1, TRUE ~ 0)) %>% 
  mutate(arbeit = case_when(str_detect(title, arbeit) ~ 1, TRUE ~ 0)) %>% 
  mutate(bildung = case_when(str_detect(title, bildung) ~ 1, TRUE ~ 0)) %>% 
  mutate(umwelt = case_when(str_detect(title, umwelt) ~ 1, TRUE ~ 0)) %>% 
  mutate(energie = case_when(str_detect(title, energie) ~ 1, TRUE ~ 0)) %>% 
  mutate(einwanderung = case_when(str_detect(title, einwanderung) ~ 1, TRUE ~ 0)) %>% 
  mutate(transport = case_when(str_detect(title, transport) ~ 1, TRUE ~ 0)) %>% 
  mutate(krimi = case_when(str_detect(title, krimi) ~ 1, TRUE ~ 0)) %>% 
  mutate(sozi = case_when(str_detect(title, sozi) ~ 1, TRUE ~ 0)) %>% 
  mutate(wohn = case_when(str_detect(title, wohn) ~ 1, TRUE ~ 0)) %>% 
  mutate(banken = case_when(str_detect(title, banken) ~ 1, TRUE ~ 0)) %>% 
  mutate(verteidigung = case_when(str_detect(title, verteidigung) ~ 1, TRUE ~ 0)) %>% 
  mutate(tech_kom = case_when(str_detect(title, tech_kom) ~ 1, TRUE ~ 0)) %>% 
  mutate(außenh = case_when(str_detect(title, außenh) ~ 1, TRUE ~ 0)) %>% 
  mutate(int_aus = case_when(str_detect(title, int_aus) ~ 1, TRUE ~ 0)) %>%
  mutate(regierung = case_when(str_detect(title, regierung) ~ 1, TRUE ~ 0)) %>% 
  mutate(public_good = case_when(str_detect(title, public_goods) ~ 1, TRUE ~ 0)) %>% 
  mutate(overlap = makroökonomie + buerger + gesundheit + agrar +
                       arbeit + bildung + umwelt + energie + einwanderung +
                       transport + krimi + sozi + wohn + banken + verteidigung +
                       tech_kom + außenh + int_aus + regierung + public_good)


df_overlap %>% 
  filter(overlap != 0) %>% 
  sjmisc::frq(overlap)

View(df_overlap %>%
  select(overlap, title, thema, file) %>% 
  filter(overlap == 2))

View(df_overlap %>%
  filter(overlap == 4))

```

# Falsches Matching korrigieren
```{r}
# für alle matches mit 3 overlaps
View(df_overlap %>%
       select(overlap, title, thema, file) %>%
       filter(overlap == 3))

df_complete_clean <- df_complete_clean %>% 
  mutate(thema = case_when(
    # wenn file == xy, dann soll x-thema zugewiesen werden
    file == "1900907" ~ "Internationale Angelegenheiten & Auslandshilfe", # terror
    file == "1903371" ~ "Außenhandel", # Waffenexporte
    file == "1902085" ~ "zSonstiges", # viel zu unspezifisch!
    file == "1800584" ~ "Außenhandel", # Handelsabkommen...
    file == "1808522" ~ "Internationale Angelegenheiten & Auslandshilfe", # steueroasen (int. Finanzm.)
    file == "1811759" ~ "Internationale Angelegenheiten & Auslandshilfe", # terror
    file == "1813162" ~ "Außenhandel", # handelsabkommen
    TRUE ~ thema)) # alle restlichen anfragen erhalten die bereits zugeordnete themen

right_matches_3 <- c("1800521")

# alle anfragen mit overlap von 2
View(df_overlap %>%
  select(overlap, title, thema, file) %>% 
  filter(overlap == 2))

df_complete_clean <- df_complete_clean %>% 
  mutate(thema = case_when(
    # wenn file == xy, dann soll x-thema zugewiesen werden
    file == "1901063" ~ "Energie", #primäres Energiethema
    file == "1802295" ~ "Außenhandel", #Wirtschaftsfolgen von Subventionen in der Landwirtschaft
    file == "1808135" ~ "Außenhandel", # Zollabbau im Zuge von ttip
    file == "1808485" ~ "Umwelt", # Klimaschutz in der Landwirtschaft
    file == "1803623" ~ "Kriminalität & Familienprobleme", #Arbeitsbedingungen für polizisten im Ausland
    file == "1805772" ~ "Internationale Angelegenheiten & Auslandshilfe", # Einfluss von d. Markt auf                                                                                    Entwicklungsländer
    file == "1808498" ~ "Soziale Wohlfahrt", #höhe von Mindestlohn zur Bekämpfung von Armut
    file == "1806954" ~ "Verteidigung", # Bundeswehrfragen
    file == "1901953" ~ "Technologie & Kommunikation", #Netzausbau
    file == "1902213" ~ "Einwanderung", #Bildungsförderung von Einwanderern
    file == "1800031" ~ "Verteidigung", # Werbung von Bundeswehr an Schulen
    file == "1800032" ~ "Verteidigung", # Ausmaß von Werbung der Bundesweh an Schulen
    file == "1801088" ~ "Verteidigung", #Bundeswehr und Schule (keine zusätzlichen Infos)
    file == "1902627" ~ "Umwelt", #Mikroplastik 
    file == "1801037" ~ "Kriminalität & Familienprobleme", #deutsch amerikanische zusammenarbeit vs Crime
    file == "1810683" ~ "Kriminalität & Familienprobleme", # irgendwas mit ppolizei
    file == "1900195" ~ "Internationale Angelegenheiten & Auslandshilfe", #Terrorismusprävention bei                                                                                   Flüchtlingen
    file == "1900564" ~ "Kriminalität & Familienprobleme", #Nutzung von interpol vs. Terrorismus 
    file == "1900606" ~ "Kriminalität & Familienprobleme", #Öffnung der Polizei gegenüber Migranten
    file == "1900783" ~ "Internationale Angelegenheiten & Auslandshilfe", #Nachklapp zu 1900195
    file == "1903675" ~ "Kriminalität & Familienprobleme", #Kriminalität von Migranten
    file == "1903824" ~ "Verteidigung", #Natoübung 
    file == "1903994" ~ "Soziale Wohlfahrt", #Renteneinstieg von Flüchtlingen 
    file == "1904307" ~ "Internationale Angelegenheiten & Auslandshilfe", # Bericht über Abschiebungen in                                                                              Madrid
    file == "1906230" ~ "Kriminalität & Familienprobleme", #Statistiken über Kriminalität von Flüchtlingen
    file == "1806872" ~ "Soziale Wohlfahrt", #Altersarmut von jüdischen Einwanderern aus der UdSSR
    file == "1811197" ~ "Verteidigung", #Bundeswehreinsatz im Libanon
    file == "1813196" ~ "Regierungsoperationen", #Kommentar zu Tschetschenien
    file == "1902876" ~ "Kriminalität & Familienprobleme", #Waffenkontrolle
    file == "1903998" ~ "Regierungsoperationen", #Twitternutzung von Regierungsmitgliedern
    file == "1904174" ~ "Gemeindeentwicklung & Wohnungsprobleme", # Wohnungspolitik
    file == "1904417" ~ "Internationale Angelegenheiten & Auslandshilfe", #Brexitfolgen
    file == "1906346" ~ "Makroökonomie", #Rundertisch zu Steuerpolitik
    file == "1900274" ~ "Transport", #Schienenpflege
    file == "1900690" ~ "Einwanderung", #Altersfeststellung von Flüchtlingen
    file == "1903065" ~ "Umwelt", #Umweltfolgen von Amalgamnutzung
    file == "1903084" ~ "Technologie & Kommunikation", #Internet in Altersheimen
    file == "1903961" ~ "Gemeindeentwicklung & Wohnungsprobleme", #eig öffentliche Flächen
    file == "1904271" ~ "Einwanderung", #Abschiebungsverzögerung durch Krankheit
    file == "1904363" ~ "Soziale Wohlfahrt", #Verschuldung durch Krankenversicherung
    file == "1806739" ~ "Transport", # Schienenpflege
    file == "1800078" ~ "Verteidigung", #Rauschmittel bei Auslandseinsätzen der Bundeswehr
    file == "1809998" ~ "Verteidigung", #Rauschmitte bei Auslandseinsätzen der Bundeswehr
    file == "1901782" ~ "Außenhandel", #Rentensteuer von Portugal
    file == "1902279" ~ "Außenhandel", #Steuerfolgen von Brexit
    file == "1905973" ~ "Regierungsoperationen", #Einflussnahme von Lobbyisten
    file == "1906354" ~ "Regierungsoperationen", #Einflussnahme von Lobbyisten
    file == "1801004" ~ "Bürgerrechte", #Steuerliche Gleichstellung von Homoehen
    file == "1804029" ~ "Regierungsoperationen", #Fischerei in Südostasien
    file == "1806230" ~ "Kriminalität & Familienprobleme", #Steuerhinterziehung
    file == "1809904" ~ "Arbeit & Beschäftigung", #Arbeitsbedingungen in der Fleischindustrie
    file == "1813367" ~ "Regierungsoperationen", #Wissenstand der Regierung über Kartellbildung
    file == "1805719" ~ "Verteidigung", #Werbung von Bundeswehr
    file == "1901455" ~ "Kriminalität & Familienprobleme", #Crime at trainstation
    file == "1901589" ~ "Kriminalität & Familienprobleme", #Crime at trainstation
    file == "1901937" ~ "Kriminalität & Familienprobleme", #Crime at trainstation
    file == "1901976" ~ "Kriminalität & Familienprobleme", #Crime in trains
    file == "1902289" ~ "Technologie & Kommunikation", #Internet in der Bahn
    file == "1903499" ~ "Kriminalität & Familienprobleme", #Crime in trains
    file == "1905695" ~ "Technologie & Kommunikation", #Internet in der Bahn
    file == "1809376" ~ "Verteidigung", # Flugshows der Bundeswehr
    file == "1812190" ~ "Kriminalität & Familienprobleme", #Crime at trainstation
    file == "1813229" ~ "Kriminalität & Familienprobleme", #Crime at trainstation
    file == "1807315" ~ "Banken, Finanzen & Binnenhandel", #Tourismusfolgen aus Klimawandel
    TRUE ~ thema)) # alle restlichen anfragen erhalten die bereits zugeordnete themen
  
# richtige Matches, jedoch dennoch vorhandener overlap
right_matches_2 <- c("file1", "file2", "file3")

```

# changing labels
```{r}
df_complete_clean %<>% 
  mutate(thema = case_when(
    thema == "Arbeit & Beschäftigung" ~ "Arbeit",
    thema == "Kriminalität & Familienprobleme" ~ "Gesetz & Kriminalität",
    thema == "Gemeindeentwicklung & Wohnungsprobleme" ~ "Wohnungsbau", 
    thema == "Banken, Finanzen & Binnenhandel" ~ "Binnenhandel", 
    thema == "Technologie & Kommunikation" ~ "Technologie", 
    thema == "Internationale Angelegenheiten & Auslandshilfe" ~ "Int. Angelegenheiten",
    thema == "Internationale Angelegenheiten" ~ "Int. Angelegenheiten",
    # str_detect(title, public_goods) ~ "Öffentliche Flächen", #20
    TRUE ~ thema
  )) %>% 
  filter(file != 1903501)

save(df_complete_clean, file = "df_complete_clean.RData")
load("df_complete_clean.RData")
```

# ggpreview
```{r}
# thanks to andrewheiss (rath; GitHub)
ggpreview <- function(..., device = "png", cairo = FALSE) {
fname <- tempfile(fileext = paste0(".", device))
if (cairo & device == "pdf") {
ggplot2::ggsave(filename = fname, device = cairo_pdf, ...)
  } else if (cairo & device == "png") {
ggplot2::ggsave(filename = fname, device = device, type = "cairo", ...)
  } else {
ggplot2::ggsave(filename = fname, device = device, ...)
  }
  system2("open", fname)
invisible(NULL)
}
```


# little inspection
```{r}
# library(ggpubr)
# figure_1 <- ggarrange(plot_18_pre, plot_19_pre,
#           labels = c("18. Bundestag", "19. Bundestag"),
#           ncol = 1, nrow = 2)
# ggsave("figure_1.png", figure_1, width = 10, height = 8)
# 
# ggpreview(figure_1, width = 10, height = 8)

# testing facet_grid() again
# creating labels
labs <- c("18. Bundestag", "19. Bundestag")
levels(df_complete_clean$bt) <- rev(labs)
df_complete_clean$bt_f <- factor(df_complete_clean$bt, labels = c("18. Bundestag", "19. Bundestag"))

# with percentage labels on the y-axis, yay
themen_gesamt_manual_matching <- df_complete_clean %>%
  filter(thema != "zSonstiges") %>%
  group_by(bt_f, thema) %>%
  summarise(n = n()) %>%
  mutate(perc = (n/sum(n))) %>%
  ggplot(aes(x = reorder(thema, +perc), y = perc)) +
  geom_bar(position = "dodge", 
           stat = "identity",
           fill = "skyblue4",
           alpha = 0.9) +
  facet_wrap(~bt_f, labeller = label_value) +
  geom_text(aes(y = perc, 
                label = sprintf("%1.1f%%", round(100*perc, 1))),
            size = 3.1,
            color=rgb(100,100,100, maxColorValue=255),
            hjust=-0.1) +
  #ylim(0,0.22)
  theme_bw() +
  ggtitle("") +
  ylab("") +
  xlab("") +
  theme(text=element_text(size = 12)) +
  scale_y_continuous(labels = scales::percent_format(), limits=c(0,0.23)) +
  coord_flip()
  
ggpreview(themen_gesamt_manual_matching, width = 7, height = 5)
ggsave("themen_gesamt_manual_matching.png", themen_gesamt_manual_matching, 
       path = "./images/", width = 7, height = 7)

```


# supervised machine
```{r}
install.packages("RTextTools")
library(RTextTools)

df_training <- df_complete_clean %>% 
  filter(thema != "zSonstiges") %>% 
  sample_n(2978)

# nrow(df_training)

# creating df with topic and content
x <- data.frame(thema = df_training$thema , content = df_training$content)
#alle Labels anzeigen
unique(x$thema)

# Erstellung einer VectorSource
source <- VectorSource(x$content)

# corpus erstellen
corpus <- Corpus(source)

# zufallsverteilung funktioniert
# corpus[[1]]$content

corpus <- tm_map(corpus, stripWhitespace)

# creating a documenttermmatrix
mat <- DocumentTermMatrix(corpus)

# train size: 80% = 2978*0.8 = 2383
container <- create_container(mat, x$thema, 
                              trainSize=1:2383,
                              testSize=2384:2978, 
                              virgin=FALSE)

model <- train_model(algorithm = "SVM", 
                     container,
                     kernel='linear')

#das Model wird auf die übrigen 20% angewendet und in results gespeichert.
results <- classify_model(container, model)

tabelle_accuracy<-table(as.character(x$thema[2384:2978]), as.character(results[,"SVM_LABEL"]))
tabelle_accuracy

recall_accuracy(x$thema[2384:2978], results[,"SVM_LABEL"])

test_tibble<-df_training[2384:2978,]
test_tibble$thema_test<-results$SVM_LABEL
test_tibble$prob<-results$SVM_PROB

length(which(test_tibble$thema==test_tibble$thema_test))/length(test_tibble$thema)
#ohne filter 0.687, N= 595

ggplot(test_tibble, aes(prob))+
  geom_histogram()+
  geom_vline(xintercept=mean(test_tibble$prob, na.rm = T), color="red")+
  geom_vline(xintercept = median(test_tibble$prob, na.rm = T), color = "blue")+
  geom_vline(xintercept = 0.6, color = "black")
```

# again but a bit better
```{r}
df_training$thema_f <- factor(df_training$thema)
df_training %<>% 
  mutate(thema_t1 = case_when(
    thema == "Energie" ~ "Energie & Umwelt",
    thema == "Umwelt" ~ "Energie & Umwelt",
    TRUE ~ thema
  ))

df_training_t2 <- df_training %>% 
  filter(thema != "Wohnungsbau" & thema != "Regierungsoperationen")

nrow(df_training_t2)

doc_matrix <- create_matrix(df_training$content)
doc_matrix_t2 <- create_matrix(df_training_t2$content)
container <- create_container(df_content_matrix, 
                              df_training_forest$thema, 
                              trainSize=1:2383,
                              testSize=2384:2977, 
                              virgin=FALSE)

container_f <- create_container(doc_matrix, 
                              as.numeric(df_training$thema_f), 
                              trainSize=1:2383,
                              testSize=2384:2978, 
                              virgin=FALSE)

svm_f <- train_model(container_f,"SVM", kernel = "linear")
svm_classify_f <- classify_model(container_f, svm_f)

# creating df with real topics, predicted topic and probability
test_svm_f <- df_training[2384:2978,]
test_svm_f$thema_test <- svm_classify_f$SVM_LABEL
test_svm_f$prob <- svm_classify_f$SVM_PROB

length(which(test_svm_f$thema==test_svm_f$thema_test))/length(test_svm_f$thema)

RTextTools::create_analytics(container_f, svm_classify_f)

df_training <- df_complete_clean %>% 
  filter(thema != "zSonstiges") %>% 
  sample_n(2977) 

# creating document-term matrix
df_content_matrix <- create_matrix(df_training$content)

# remove sparse terms: In this case tokens are removed which are missing from more than 99% of the documents
df_content_matrix <- removeSparseTerms(df_content_matrix, sparse = .99)

container <- create_container(df_content_matrix, 
                              df_training$thema, 
                              trainSize=1:2383,
                              testSize=2384:2977, 
                              virgin=FALSE)

# SVM Algortihm
svm <- train_model(container,"SVM")
svm_classify <- classify_model(container, svm)

# creating df with real topics, predicted topic and probability
test_svm <- df_training[2384:2977,]
test_svm$thema_test <- svm_classify$SVM_LABEL
test_svm$prob <- svm_classify$SVM_PROB

length(which(test_svm$thema==test_svm$thema_test))/length(test_svm$thema)
#ohne filter 0.687 (1), 0.744 (2), N= 595

# looking for probabilities
test_svm_04<- test_svm %>%
  filter(prob >= 0.4)%>%
  arrange((prob))
length(which(test_svm_04$thema==test_svm_04$thema_test))/length(test_svm_04$thema)
# 81.9; n = 420 -> 70.6%

test_svm_05 <- test_svm %>%
  filter(prob >= 0.5)%>%
  arrange((prob))
length(which(test_svm_05$thema==test_svm_05$thema_test))/length(test_svm_05$thema)
# 86.2; n = 364 -> 61.2% (von 595)

test_svm_06<- test_svm %>%
  filter(prob >= 0.6)%>%
  arrange((prob))
length(which(test_svm_06$thema==test_svm_06$thema_test))/length(test_svm_06$thema)
nrow(test_svm_06)/nrow(test_svm)
# 90.3; n = 310 -> 52% (von 595)
# 2. durchlauf: 0.912; n = 307 -> 52%...


test_svm_07<- test_svm %>%
  filter(prob >= 0.7)%>%
  arrange((prob))
length(which(test_svm_07$thema==test_svm_07$thema_test))/length(test_svm_07$thema)
nrow(test_svm_07)
# 92.7%; n = 263 -> 44% (von 595)


test_svm_08<- test_svm %>%
  filter(prob >= 0.8)%>%
  arrange((prob))
length(which(test_svm_08$thema==test_svm_08$thema_test))/length(test_svm_08$thema)
# 94.1%; n = 190 -> 31.9% (von 595)

test_svm_085<- test_tibble%>%
  filter(prob>=0.85)%>%
  arrange((prob))
length(which(test_svm_085$thema==test_svm_085$thema_test))/length(test_svm_085$thema)
# 95.7%; n = 186 -> 31.2% (von 595)


test_svm_09 <- test_svm %>%
  filter(prob >= 0.9)%>%
  arrange((prob))
length(which(test_svm_09$thema==test_svm_09$thema_test))/length(test_svm_09$thema)
# 98,6% n = 146 -> 24,5% (von 595)

# RF Algorithm
rf <- train_model(container, "RF")
rf_classify <- classify_model(container, rf)

# creating df with real topics, predicted topic and probability
test_rf <- df_training[2384:2977,]
test_rf$thema_test <- rf_classify$FORESTS_LABEL
test_rf$prob <- rf_classify$FORESTS_PROB

length(which(test_rf$thema==test_rf$thema_test))/length(test_rf$thema)

test_rf_05 <- test_rf  %>% 
  filter(prob >= 0.5) %>% 
  arrange((prob))
length(which(test_rf_05$thema==test_rf_05$thema_test))/length(test_rf_05$thema)
nrow(test_rf_05)/nrow(test_rf)

test_rf_06 <- test_rf  %>% 
  filter(prob >= 0.6) %>% 
  arrange((prob))
length(which(test_rf_06$thema==test_rf_06$thema_test))/length(test_rf_06$thema)
nrow(test_rf_06)/nrow(test_rf)


test_rf %>% 
  group_by(thema) %>% 
  summarise(prob_m = mean(prob)) %>% 
  arrange(desc(prob_m))

View(df_complete_clean %>% 
  filter(thema == "Bürgerrechte") %>% 
    select(title, file))

```

# data correction
```{r}
# Bürgerrechte
View(df_complete_clean %>% 
  filter(thema == "Bürgerrechte") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1801391 ~ "Agrarwirtschaft", # Tierschutz (domestizierte Tiere)
    file == 1807122 ~ "zSonstiges", # falsche Zuordnung
    file == 1808719 ~ "zSonstiges",
    file == 1809586 ~ "zSonstiges",
    TRUE ~ thema
  ))

# Binnenhandel
View(df_complete_clean %>% 
  filter(thema == "Binnenhandel") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1904256 ~ "Int. Angelegenheiten", # türk. Kapitalmarkt
    file == 1906264 ~ "Int. Angelegenheiten", # USA und lockerung Bankenaufsicht
    file == 1801588 ~ "Int. Angelegenheiten", # palmöl, entwicklungsbank
    file == 1804267 ~ "Gesetz & Kriminalität", # bankenraub
    file == 1805648 ~ "Int. Angelegenheiten", # kasachstan uran-bank
    file == 1808153 ~ "Gesetz & Kriminalität", # europol
    TRUE ~ thema
  ))

# Regierungsoperationen
View(df_complete_clean %>% 
  filter(thema == "Regierungsoperationen") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1804029 ~ "Int. Angelegenheiten", # Menschenrechtsverletzungen
    TRUE ~ thema
  ))

# Wohnungsbau
View(df_complete_clean %>% 
  filter(thema == "Wohnungsbau") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1903688 ~ "Gesetz & Kriminalität", # Gewalt gg Obdachlose
    file == 1903961 ~ "Umwelt", # Klimawandel
    file == 1801525 ~ "Regierungsoperationen", # bundesanstalt für immobilien
    TRUE ~ thema
  ))

# Agrarwirtschaft
View(df_complete_clean %>% 
  filter(thema == "Agrarwirtschaft") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1900419 ~ "Int. Angelegenheiten", # Arbeitsbedingungen globaler Süden
    file == 1904410 ~ "zSonstiges", # Brexit und Auswirkungen auf Landwirtschaft
    file == 1803640 ~ "zSonstiges", # Netzbetreiber & Rückforderung
    file == 1809006 ~ "Int. Angelegenheiten", # Agrarwirtschaft Iran
    TRUE ~ thema
  ))

# Umwelt
View(df_complete_clean %>% 
  filter(thema == "Umwelt") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1900637 ~ "Transport", # Verzögerung Bau Autobahnen
    file == 1901171 ~ "Agrarwirtschaft", # Schächtung -> Tierschutz domestiziert
    file == 1902380 ~ "Int. Angelegenheiten", # Menschenrechte etc.
    file == 1902636 ~ "zSonstiges", # nicht zu spezifizieren
    file == 1902843 ~ "Energie", # Stromnetze...
    file == 1905410 ~ "Int. Angelegenheiten", # tunesien etc. 
    file == 1905966 ~ "Regierungsoperationen", # Einfluss Lobby auf Gesetz
    file == 1802043 ~ "Int. Angelegenheiten", # außenwirtschaft, menschenrechte
    file == 1803692 ~ "Energie", # veränderungen Energiewirtschaft
    file == 1809393 ~ "Transport", # LKW -> eher Transport
    file == 1810134 ~ "Transport", # Ausbau einer Bundesstraße
    file == 1811148 ~ "Int. Angelegenheiten", # Nambia, Menschenrechte und etwas Umweltschutz
    file == 1812228 ~ "Agrarwirtschaft", # Tierschutz von domestizierten Tieren
    TRUE ~ thema
  ))

# Soziale Wohlfahrt
View(df_complete_clean %>% 
  filter(thema == "Soziale Wohlfahrt") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1902260 ~ "zSonstiges", # falsches Matching
    file == 1902257 ~ "zSonstiges", # falsches Matching
    file == 1812713 ~ "Gesundheit", # definitiv Gesundheit
    TRUE ~ thema
  ))

# Makroökonomie -> hier dürfte einiges nicht ganz richtig sein
View(df_complete_clean %>% 
  filter(thema == "Makroökonomie") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1903237 ~ "zSonstiges", # flagschiffe...
    file == 1904143 ~ "Gesundheit", # Pharma, Ärzte...Qualitätssicherung
    file == 1805668 ~ "Energie", # Stromnetze
    file == 1811916 ~ "zSonstiges", # Türkei und Panzer
    TRUE ~ thema
  )) # Überraschend wenig falsch

# Energie
View(df_complete_clean %>% 
  filter(thema == "Energie") %>% 
    select(title, file))
# Nix, jedoch einige Themen, die man evtl. auch Umwelt zuordnen könnte

# Bildung
View(df_complete_clean %>% 
  filter(thema == "Bildung") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1900617 ~ "Bürgerrechte", # antisemitismus
    TRUE ~ thema
  ))

# zSonstiges (manuelles Matching zwecks Verbesserung)
View(df_complete_clean %>% 
  filter(thema == "zSonstiges") %>% 
    select(title, file))

df_complete_clean %<>% 
  mutate(thema = case_when(
    file == 1900065 ~ "Int. Angelegenheiten", # Terror
    file == 1900129 ~ "Bürgerrechte", # Grundordnung Demokratie - Antifaschismus
    file == 1900202 ~ "Int. Angelegenheiten", # Unabhängigkeit Katalonien 
    file == 1900264 ~ "Umwelt", # Verpackungsabfallaufkommen
    file == 1900290 ~ "Regierungsoperationen", # Staatsbesuche
    file == 1900121 ~ "Umwelt", # Stickoxide
    file == 1900369 ~ "Arbeit", # flexibles Arbeiten
    file == 1900376 ~ "Transport", # S21
    file == 1900627 ~ "Int. Angelegenheiten", # Libyen
    file == 1900664 ~ "Int. Angelegenheiten", # Syrien
    file == 1900782 ~ "Int. Angelegenheiten", # Entwicklungshilfe
    file == 1900801 ~ "Transport", # S21
    file == 1901122 ~ "Int. Angelegenheiten", # Brasilien
    file == 1901251 ~ "Soziale Wohlfahrt", # Ruhestand
    file == 1901324 ~ "Bürgerrechte", # gleichberechtigung
    file == 1901387 ~ "Umwelt", # Kunststoffabfälle
    file == 1901417 ~ "Transport", # Güterzüge
    file == 1901444 ~ "Bürgerrechte", # Schwerbehinderte
    file == 1901496 ~ "Makroökonomie", # Unternehmen
    file == 1901525 ~ "Technologie", # KI
    file == 1901579 ~ "Int. Angelegenheiten", # Türkei und Lage
    file == 1901612 ~ "Int. Angelegenheiten", # Islamisten
    file == 1901615 ~ "Technologie", # Satelliten
    file == 1901619 ~ "Gesundheit", # Geburtshilfe
    file == 1901652 ~ "Gesetz & Kriminalität", # Verdächtige G20
    file == 1901864 ~ "Umwelt", # Luftschadstoffe und Allergien
    file == 1901945 ~ "Transport", # Zukunft Berlin Tegel
    file == 1901946 ~ "Makroökonomie", # Schiffahrtsmarkt
    file == 1901975 ~ "Binnenhandel", # Regulierung Kryptowährungen
    file == 1902031 ~ "Verteidigung", # militärische Übungsflüge
    file == 1902065 ~ "Int. Angelegenheiten", # Lage Kosovo
    file == 1902104 ~ "Soziale Wohlfahrt", # sgb ii
    file == 1903656 ~ "Bürgerrechte", # Beteiligung
    file == 1903876 ~ "Transport", # E-Mobilität
    file == 1904065 ~ "Gesundheit", # gesundheitliche Versorgung
    file == 1904111 ~ "Einwanderung", # Flüchtlinge
    file == 1904315 ~ "Gesundheit", # korruption Gesundheitswesen
    file == 1904652 ~ "Transport", # Luftverkehrskonzept
    file == 1904683 ~ "Arbeit", # Lohnquote
    file == 1904938 ~ "Gesetz & Kriminalität", # kriminelle Familienclans
    file == 1905497 ~ "Einwanderung", # Geflüchtete
    file == 1905708 ~ "Wohnungsbau", # Bauland und Leerstand
    file == 1906259 ~ "Umwelt", # Lichtverschmutzung
    file == 1906282 ~ "Technologie", # Mobilfunkstandard 5G
    file == 1800696 ~ "Arbeit", # Befrsitung Arbeitsverträge
    file == 1800730 ~ "Soziale Wohlfahrt", # Alterssicherung
    file == 1800805 ~ "Transport", # Ausbau Bundesstraße 
    file == 1800918 ~ "Int. Angelegenheiten", # Kambodscha
    file == 1801001 ~ "Soziale Wohlfahrt", # Elterngeld
    file == 1801138 ~ "Transport", # S21
    file == 1801139 ~ "Transport", # S21
    file == 1801150 ~ "Int. Angelegenheiten", # Piraterie Horn Afrika
    file == 1801906 ~ "Transport", # Grostransporte, Infrastruktur
    file == 1802044 ~ "Umwelt", # Bioabfall und Verwertung
    file == 1802072 ~ "Transport", # autonomes Fahren
    file == 1802718 ~ "Umwelt", # Überfischung
    file == 1802801 ~ "Int. Angelegenheiten", # IS
    file == 1803239 ~ "Umwelt", # Meeresschutz
    file == 1805674 ~ "Agrarwirtschaft", # Fischerei
    file == 1805749 ~ "Umwelt", # Gewässerbelastung
    file == 1806429 ~ "Einwanderung", # geflüchtete Frauen i. Deutschland
    file == 1807153 ~ "Int. Angelegenheiten", # Saudi Arabien und IS
    file == 1807463 ~ "Transport", # Güterverkehr und Logistik
    file == 1807506 ~ "Arbeit", # Minijobs
    file == 1807507 ~ "Arbeit", # Beschäftigung
    file == 1807631 ~ "Transport", # Verkehr und Infrastruktur
    file == 1807745 ~ "Umwelt", # Gewässerqualität und Einhaltung
    file == 1808329 ~ "Umwelt", # Gewässerqualität und Einhaltung
    file == 1808330 ~ "Umwelt", # Gewässerqualität und Einhaltung
    file == 1808465 ~ "Gesundheit", # Alkoholprävention
    file == 1808792 ~ "Umwelt", # Gewässerqualität
    file == 1808970 ~ "Einwanderung", # Geburtsurkunde Flüchtlingskinder
    file == 1809361 ~ "Binnenhandel", # Fintechs
    file == 1809426 ~ "Bürgerrechte", # Beteiligung von Behinderten
    file == 1809468 ~ "Arbeit", # home office
    file == 1810136 ~ "Transport", # Bundesstraße Ausbau
    file == 1810834 ~ "Bürgerrechte", # Antisemitismus
    file == 1811819 ~ "Gesetz & Kriminalität", # Fahrraddiebstahl
    file == 1813112 ~ "Arbeit", # Minijobs
    file == 1813524 ~ "Arbeit", # Lohntentwicklung
    TRUE ~ thema
  ))

# Große Anfragen komplett raus
df_complete_clean %<>% 
  filter(type != "Große Anfrage")

# saving new data
df_complete_clean_v2 <- df_complete_clean

save(df_complete_clean_v2, file = "df_complete_clean_v2.RData")
load("df_complete_clean_v2.RData")
```

# train model again with new df
```{r}
load("df_complete_clean_v2.RData")

df_training_v2 <- df_complete_clean_v2 %>% 
  filter(thema != "zSonstiges") %>% 
  sample_n(3047) 

3047*0.75

# creating document-term matrix
df_content_matrix_v2 <- create_matrix(df_training_v2$content)

# remove sparse terms: In this case tokens are removed which are missing from more than 99% of the documents
df_content_matrix_v2 <- removeSparseTerms(df_content_matrix_v2, sparse = .99)

container_v2 <- create_container(df_content_matrix_v2, 
                              df_training_v2$thema, 
                              trainSize=1:2300,
                              testSize=2301:3047, 
                              virgin=FALSE)

# SVM Algortihm
svm_v2 <- train_model(container_v2,"SVM")
svm_classify_v2 <- classify_model(container_v2, svm_v2)

# creating df with real topics, predicted topic and probability
test_svm_v2 <- df_training_v2[2301:3047,]
test_svm_v2$thema_test <- svm_classify_v2$SVM_LABEL
test_svm_v2$prob <- svm_classify_v2$SVM_PROB

length(which(test_svm_v2$thema==test_svm_v2$thema_test))/length(test_svm_v2$thema)
# 70,9%

# looking for probabilities
test_svm_prob_v2 <- test_svm_v2 %>%
  filter(prob >= 0.9)%>%
  arrange((prob))
length(which(test_svm_prob_v2$thema==test_svm_prob_v2$thema_test))/length(test_svm_prob_v2$thema)
nrow(test_svm_prob_v2)/nrow(test_svm_v2)
# 0.3: 0.7953 richtig / 0.8046 Matching
# 0.4: 0.8475 richtig / 0.6760 Matching
# 0.5: 0.8762 richtig / 0.5730 Matching
# 0.6: 0.9008 richtig / 0.4859 Matching
# 0.7: 0.9126 richtig / 0.4137 Matching
# 0.8: 0.9333 richtig / 0.3414 Matching
# 0.9: 0.9494 richtig / 0.2383 Matching


# RF Algorithm
rf_v2 <- train_model(container_v2, "RF")
rf_classify_v2 <- classify_model(container_v2, rf_v2)

# creating df with real topics, predicted topic and probability
test_rf_v2 <- df_training_v2[2301:3047,]
test_rf_v2$thema_test <- rf_classify_v2$FORESTS_LABEL
test_rf_v2$prob <- rf_classify_v2$FORESTS_PROB

length(which(test_rf_v2$thema==test_rf_v2$thema_test))/length(test_rf_v2$thema)
# 71,88% 

test_rf_200 <- test_rf_v2  %>% 
  filter(prob >= 0.3) %>% 
  arrange((prob))
length(which(test_rf_200$thema==test_rf_200$thema_test))/length(test_rf_200$thema)
nrow(test_rf_200)/nrow(test_rf_v2)
# 0.3: 0.8389 richtig / 0.7483 Matching
# 0.4: 0.9007 richtig / 0.5800 Matching
# 0.5: 0.9421 richtig / 0.4163 Matching
# 0.6: 0.9773 richtig / 0.2945 Matching
# 0.7: 1 richtig / 0.1954 Matching
# 0.8: 1 richtig / 0.1312 Matching
# 0.9: 1 richtig / 0.0977 Matching

rf_v2_500 <- train_model(container_v2, "RF", ntree = 500)
rf_classify_v2_500 <- classify_model(container_v2, rf_v2_500)

# creating df with real topics, predicted topic and probability
test_rf_v2_500 <- df_training_v2[2301:3047,]
test_rf_v2_500$thema_test <- rf_classify_v2_500$FORESTS_LABEL
test_rf_v2_500$prob <- rf_classify_v2_500$FORESTS_PROB

length(which(test_rf_v2_500$thema==test_rf_v2_500$thema_test))/length(test_rf_v2_500$thema)
# 72,55

test_rf_500 <- test_rf_v2_500  %>% 
  filter(prob >= 0.3) %>% 
  arrange((prob))
length(which(test_rf_500$thema==test_rf_500$thema_test))/length(test_rf_500$thema)
nrow(test_rf_500)/nrow(test_rf_v2_500)
# 0.3: 0.8496 richtig / 0.7389 Matching
# 0.4: 0.8947 richtig / 0.5850 Matching
# 0.5: 0.9308 richtig / 0.4257 Matching
# 0.6: 0.9733 richtig / 0.3012 Matching
# 0.7: 0.9933 richtig / 0.1995 Matching
# 0.8: 1 richtig / 0.1338 Matching
# 0.9: 1 richtig / 0.0991 Matching

rf_v2_800 <- train_model(container_v2, "RF", ntree = 800)
rf_classify_v2_800 <- classify_model(container_v2, rf_v2_800)

# creating df with real topics, predicted topic and probability
test_rf_v2_800 <- df_training_v2[2301:3047,]
test_rf_v2_800$thema_test <- rf_classify_v2_800$FORESTS_LABEL
test_rf_v2_800$prob <- rf_classify_v2_800$FORESTS_PROB

length(which(test_rf_v2_800$thema==test_rf_v2_800$thema_test))/length(test_rf_v2_800$thema)
# 72,55

test_rf_800 <- test_rf_v2_800  %>% 
  filter(prob >= 0.9) %>% 
  arrange((prob))
length(which(test_rf_800$thema==test_rf_800$thema_test))/length(test_rf_800$thema)
nrow(test_rf_800)/nrow(test_rf_v2_800)

test_rf %>% 
  group_by(thema) %>% 
  summarise(prob_m = mean(prob)) %>% 
  arrange(desc(prob_m))
```


```{r}
ggplot(df_complete_clean, aes(thema)) +
  geom_bar(position="dodge")

df_complete_clean %>%
  filter(thema != "zSonstiges") %>%
  group_by(party, thema) %>%
  filter(party != "SPD" & party != "Union" & party != "NA") %>% 
  summarise(n = n()) %>%
  mutate(perc = (n/sum(n))) %>%
  mutate(thema = fct_reorder2(thema, party, perc)) %>% 
  ggplot(aes(x = thema, y = perc)) +
  geom_bar(position = "dodge",
           stat = "identity",
           fill = "skyblue4") +
  facet_wrap(~party, labeller = label_value) +
  geom_text(aes(y = perc, 
                label = sprintf("%1.1f%%", round(100*perc, 1))),
            size = 3.1,
            color=rgb(100,100,100, maxColorValue=255),
            hjust=-0.1) +
  #ylim(0,0.22)
  theme_bw() +
  theme(text=element_text(size = 12)) +
  scale_y_continuous(labels = scales::percent_format()) +
  coord_flip()

unique(df_complete_clean$party)

```

## inspecting data again
```{r}
head(df_complete_clean$content, 30)

added_stopwords <- as.data.frame(c("umso", "gilt", "inwiefern", "inwieweit", "ren", "wa", "len", 
                                   "de", "nen", "lich", "jewei", "mach", "ten", "wel", "ches",
                                   "wwwprintsystemdevertrieb", "be", "re"))

colnames(added_stopwords) <- "word"
added_stopwords <- as.character(added_stopwords$word)

df_complete_clean$content %<>% 
  removeWords(added_stopwords)

View(df_complete_clean %>% 
  select(thema, title, file) %>% 
  filter(thema == "zSonstiges"))

df_complete_clean %>% 
  group_by(bt) %>% 
  summarise(n = n())
```


