---
title: "Untitled"
author: "Marlon Schumacher"
date: "22 2 2019"
output: html_document
---


## some packages
```{r}
install.packages("SentimentAnalysis")
p_load(dplyr, haven, readr, ggplot2, pdftools, stringr, lubridate, RColorBrewer, tm, ggthemes, RTextTools,
       caret, randomForest, magrittr, forcats, SentimentAnalysis)
```



```{r}
load("df_complete_clean_v2.RData")
load("df_complete_clean_f.RData")
load("df_complete_clean.RData")

sentiment <- analyzeSentiment(df_complete_clean_f$content[1:10], language = "german")

sentiment$SentimentQDAP
```

## importing SentiWS
```{r}
neg_df <- read_tsv("./SentiWS_v2/SentiWS_v2.0_Negative.txt", col_names = FALSE)
names(neg_df) <- c("Wort_POS", "Wert", "Inflektionen")

neg_df %<>% 
  mutate(Wort = str_sub(Wort_POS, 1, regexpr("\\|", .$Wort_POS)-1),
         POS = str_sub(Wort_POS, start = regexpr("\\|", .$Wort_POS)+1)) %>% 
  select(-Wort_POS)

pos_df <- read_tsv("./SentiWS_v2/SentiWS_v2.0_Positive.txt", col_names = FALSE)
names(pos_df) <- c("Wort_POS", "Wert", "Inflektionen")

pos_df %<>% 
  mutate(Wort = str_sub(Wort_POS, 1, regexpr("\\|", .$Wort_POS)-1),
         POS = str_sub(Wort_POS, start = regexpr("\\|", .$Wort_POS)+1))

sentiment_df <- bind_rows("neg" = neg_df, "pos" = pos_df, .id = "neg_pos") %>% 
  select(neg_pos, Wort, Wert, Inflektionen, -Wort_POS) %>% 
  mutate(Wort = tolower(Wort),
         Inflektionen = tolower(Inflektionen))

# removing duplicates
sentiment_df_2 <- sentiment_df %>% 
  mutate(duplicate = duplicated(Wort)) %>% 
  filter(duplicate != TRUE)
```

## creating custom sentiment dictonary
```{r}
# creating two types of dictionaries
sentiment_dictionary <- SentimentDictionaryWeighted(sentiment_df_2$Wort, sentiment_df_2$Wert)
senti_dict_binary <- SentimentDictionaryBinary(pos_df$Wort, neg_df$Wort)

# splitting df because memory can't handle the amount of data
df_sonst_f <- df_complete_clean_f %>% 
  filter(label == "Sonstiges")

df_lab_f <- df_complete_clean_f %>% 
  filter(label != "Sonstiges")

# sentiment analysis for the two splitted parts of the df
df_lab_f$sentiment <- analyzeSentiment(df_lab_f$content, rules=list("Amplifiers"=list(ruleSentiment,
                                                                                  senti_dict_binary)))[,1]

df_sonst_f$sentiment <- analyzeSentiment(df_sonst_f$content, rules=list("Amplifiers"=list(ruleSentiment,
                                                                                  senti_dict_binary)))[,1]

# combining splitted df with sentiment-scores
df_complete_fin <- rbind(df_lab_f, df_sonst_f)

# sentiment analysis for the two splitted parts of the df
df_lab_f$sentiment2 <- analyzeSentiment(df_lab_f$content, rules=list("Amplifiers"=list(ruleSentimentPolarity,
                                                                                  senti_dict_binary)))[,1]

df_sonst_f$sentiment2 <- analyzeSentiment(df_sonst_f$content, rules=list("Amplifiers"=list(ruleSentimentPolarity,
                                                                                  senti_dict_binary)))[,1]

# ruleSentimentPolarity()
# diff <- p - n
# more positive words than negative words = positive value
# more negative words than positive words = negative value

# combining splitted df with sentiment-scores
df_complete_fin <- rbind(df_lab_f, df_sonst_f)

save(df_complete_fin, file = "df_complete_fin.RData")
load("df_complete_fin.RData")
```

## inspecting sentiments
```{r}
my_comparisons <- list( c("AfD", "Linke"), c("AfD", "Grüne"), c("AfD", "FDP"), 
                        c("FDP", "Linke"), c("FDP", "Grüne"), c("Grüne", "Linke"))

df_complete_fin %>% 
  filter(label == "Gesetz & Kriminalität" & party != "SPD" & party != "Union") %>% 
  group_by(party) %>% 
  ggplot(., aes(x = party, y = sentiment, col = party)) +
  geom_boxplot() +
  ggpubr::stat_compare_means(comparisons = my_comparisons) +
  scale_color_manual(values = c("Grüne" = "#50822E", "Linke" = "#B61C3E", 
                     "CDU/CSU" = "#32372C", "SPD" = "#E3000F", "AfD" = "#0088FF", "FDP" = "#FFD600")) +
  theme_bw() 

df_complete_fin %>% 
  filter(party != "SPD" & party != "Union") %>% 
  filter(label == "Gesetz & Kriminalität" | label == "Einwanderung" | label == "Umwelt" | label == "Transport") %>% 
  group_by(label, party) %>% 
  ggplot(., aes(x = party, y = sentiment, col = party)) +
  geom_boxplot() +
  ggpubr::stat_compare_means(comparisons = my_comparisons) +
  scale_color_manual(values = c("Grüne" = "#50822E", "Linke" = "#B61C3E", 
                     "CDU/CSU" = "#32372C", "SPD" = "#E3000F", "AfD" = "#0088FF", "FDP" = "#FFD600")) +
  theme_bw() +
  facet_wrap(~label) 

df_complete_fin %>% 
  filter(party != "SPD" & party != "Union") %>% 
  filter(label == "Gesetz & Kriminalität" | label == "Einwanderung") %>% 
  group_by(label, party) %>% 
  ggplot(., aes(x = party, y = sentiment2, col = party)) +
  geom_boxplot(alpha = 1, width = 0.2) +
  geom_violin(alpha = 0.3) +
  labs(fill ="") +
  ggpubr::stat_compare_means(comparisons = my_comparisons, bracket.size = 0.3, size = 3.5, 
                             text = element_text(family = "LM Roman 10")) +
  scale_color_manual(values = c("Grüne" = "#50822E", "Linke" = "#B61C3E", 
                     "CDU/CSU" = "#32372C", "SPD" = "#E3000F", "AfD" = "#0088FF", "FDP" = "#FFD600")) +
  theme_bw() +
  theme(text=element_text(size = 12, family = "LM Roman 10"), 
        plot.margin=grid::unit(c(0,0,0,0), "mm"),
        axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        legend.position = "bottom") +
  facet_wrap(~label) 


df_complete_fin %>% 
  filter(party != "SPD" & party != "Union") %>% 
  filter(label == "Gesetz & Kriminalität" | label == "Einwanderung" | label == "Umwelt" | label == "Transport") %>% 
  group_by(label, party) %>% 
  ggplot(., aes(x = party, y = sentiment2, col = party)) +
  geom_boxplot(alpha = 1, width = 0.2) +
  geom_violin(alpha = 0.3) +
  labs(fill ="") +
  ggpubr::stat_compare_means(comparisons = my_comparisons, bracket.size = 0.3, size = 3.5, 
                             text = element_text(family = "LM Roman 10")) +
  scale_color_manual(values = c("Grüne" = "#50822E", "Linke" = "#B61C3E", 
                     "CDU/CSU" = "#32372C", "SPD" = "#E3000F", "AfD" = "#0088FF", "FDP" = "#FFD600")) +
  theme_bw() +
  theme(text=element_text(size = 12, family = "LM Roman 10"), 
        plot.margin=grid::unit(c(0,0,0,0), "mm"),
        axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        legend.position = "bottom") +
  facet_wrap(~label) 


sentiment_party <- df_complete_fin %>% 
  filter(party != "SPD" & party != "Union") %>% 
  filter(label == "Gesetz & Kriminalität" | label == "Einwanderung" | label == "Umwelt" | label == "Transport" | 
           label == "Verteidigung" | label == "Energie") %>% 
  group_by(label, party) %>% 
  ggplot(., aes(x = party, y = sentiment2, col = party)) +
  geom_boxplot(alpha = 1, width = 0.2) +
  geom_violin(alpha = 0.3) +
  labs(fill ="") +
  ggpubr::stat_compare_means(comparisons = my_comparisons, bracket.size = 0.3, size = 3, 
                             text = element_text(family = "LM Roman 10")) +
  scale_color_manual(values = c("Grüne" = "#50822E", "Linke" = "#B61C3E", 
                     "CDU/CSU" = "#32372C", "SPD" = "#E3000F", "AfD" = "#0088FF", "FDP" = "#FFD600")) +
  theme_bw() +
  theme(text=element_text(size = 12, family = "LM Roman 10"), 
        plot.margin=grid::unit(c(0,0,0,0), "mm"),
        axis.title.x=element_blank(),
        axis.title.y = element_blank(),
        legend.position = "bottom") +
  facet_wrap(~label) 

ggpreview(sentiment_party, width = 12, height = 8)
ggsave("sentiment_party.png", sentiment_party,
       path = "./images/", width = 12, height = 8)

args(ggpubr::stat_compare_means)

```

