---
output: pdf_document
---

## Issue Ownership 

In diesem Abschnitt soll zunächst die Theorie der *Issue Ownership* erläutert werden. Dafür werden zunächst die Anfänge erläutert, um dann zu den Kernthesen und Dimensionen der Theorie zu gelangen. Im darauffolgenden Schritt werden die Hypothesen für diese wissenschaftliche Arbeit anhand der *Issue Ownership* Theorie formuliert und erläutert. Anschließend wird der aktuelle Forschungsstand näher beleuchtet. Hierbei soll die Frage beantwortet werden, welche Forschung in der Vergangenheit bereits getätigt wurde.

### Theorie & Hypothesen

Die Theorie der *Issue Ownership* erlangte 1983 erstmals in dem Buch *Explaining and predicting elections: Issue effects and party strategies in twenty-three democracies* von Ian Budge und Dennis Farlie in den Politikwissenschaften an Bekanntheit [vgl. @lefevere2015introduction 2]. Die beiden Autoren sind mit dem Wissenschaftler John R. Petrocik die meistzitiertesten Autoren in der *Issue Ownership* Forschung und können somit als Grundväter dieser Forschung gewertet werden. Ziel dieser Theorie ist es zum einen zu erklären wie sich Parteien und Kandidaten verhalten, die sich in Wahlen auf einzelne Themen fokussieren, welche von den Parteien vorgegeben wurden. Das andere Ziel ist es, das Wahlverhalten bezüglich *Issue Ownership* zu analysieren [vgl. @belanger2008issue 2]. 

Die Wissenschaftler Budge und Farlie beschreiben *Issue Ownership* als die Wahrnehmung von Wählern, der zufolge eine Partei in einem Themengebiet mehr Kompetenzen besitzt als andere Parteien im jeweiligen Wahlsystem. Dabei spiegelt *Issue Ownership* für Budge und Farlie eine stabile und positive Evaluation von Wählern wieder, nach der Parteien in spezifischen Themenbereichen ihre politischen Ideen umsetzen können [vgl. @stubager2017issue 347]. Petrocik beschreibt *Issue Ownership* auf ähnliche Weise. Für ihn entstammt *Issue Ownership* aus der Fähigkeit bestimmter Parteien gewisse Probleme in dem Themenfeld zu lösen. Die Parteien erhalten diese Befähigung, indem  sie in diesen Themenfeldern mehr Aufmerksamkeit, Initiative und Innovationen bezüglich der Probleme aufzeigen [vgl. @walgrave2012associative 772]. Der erhöhte Ressourcenaufwand führt dazu, dass die Wähler auf lange Sicht diesen Parteien mehr Handlungs- und Wissenskompetenzen in den Themen einräumen. Dabei kann die Affiliation zwischen den Parteien und den Themen aus kurzfristigen und langfristigen Quellen stammen. Petrocik nennt diese Formen *record of incumbent* und *constituencies of the parties* [Petrocik zitiert nach @stubager2017issue 348]. Beim *record of incumbent* zählen alle Errungenschaften und Schwierigkeiten von Parteien bezüglich der Lösung von Problemen hinzu. Das Problem hierbei ist, dass unvorhergesehene Ereignisse Schwierigkeiten hervorrufen können, welche nicht von den Parteien ausgelöst wurden und bewältigt werden können, auch wenn die Partei erhöhte Kompetenzen im jeweiligen Themenbereich besitzt. Deswegen wird der *record of incumbent* als instabil eingeschätzt [vgl. @stubager2017issue 348]. Im Kontrast hierzu ist die *constituencies of the parties* sehr viel stabiler. Die Grundlage liegt dabei in den stabilen aber unterschiedlichen sozialen Wählerschaften und der Verbindung zwischen politischen Konflikten und sozialen Strukturen [Petrocik zitiert nach @stubager2017issue 348]. 

In jüngeren Studien von Walgrave, Lefevere und Tresch aus dem Jahr 2012 wird nochmals zwischen zwei Analysedimensionen der *Issue Ownership* differenziert. Die erste Dimension bezieht sich auf den Kompetenzaspekt von Parteien in den jeweiligen Themen. Die zweite Dimension betrifft den Assoziationsaspekt von Parteien für gewisse Themen [vgl. @walgrave2012associative 772]. Beide Dimensionen wurden schon von Budge & Farlie und Petrocik in ihren Werken verwendet. Walgrave et al. kritisieren jedoch, dass beide Dimensionen kombiniert und zeitgleich untersucht werden. Stattdessen sollten beide Dimensionen getrennt gemessen und untersucht werden, um die *Issue Ownership* in vollem Umfang analysieren zu können. Dieses Argument unterstreichen die Autoren mit empirischen Befunden [vgl. @walgrave2012associative 779]. Ein anderer relevanter Faktor ist die Frage, ob klare thematische Monopole existieren. Falls eine Partei eine klare Dominanz über ein Thema besitzt, schlägt sich dies auch in Wahlen nieder, wenn das Thema salient ist [vgl. @geys2012success 4]. Zum anderen können auch Parteien ein Thema unter sich aufteilen. Dabei würden verschiedene Wählerbasen mit eigenen Grundansichten verschiedene Parteien bezüglich eines Themas präferieren [vgl. @geys2012success 5]. Jedoch können auch hier Hierarchien bezüglich der Einschätzung der Kompetenz von Parteien und der Wertigkeit der Assoziationen auftreten. 

Eines der Hauptprobleme der empirischen Analyse der *Issue Ownership* in Deutschland ist die Messung der Themen. Diese findet in der breiten Forschung durch Survey Fragen statt, mit welchen herausgefunden wird inwiefern Parteien erhöhte Kompetenzen in einem Themenfeld besitzen und ob Parteien mit spezifischen Themen assoziiert werden. Für Deutschland liegen hierfür jedoch keine Daten vor. Mit dieser Problematik setzt sich auch die vorliegende Arbeit auseinander. Können kleine Anfragen für den Bundestag als Messmethode für die *Issue Ownership* Theorie benutzt werden? Ein anderer wichtiger Aspekt, der nicht in der breiten Forschung diskutiert wird, sind die behandelten Themen der Parteien in der politischen Arbeit. Wie positionieren sich die Oppositionsparteien im deutschen Bundestag? Hierbei kann davon ausgegangen werden, dass der Fokus der Parteien sich nicht gleichmäßig auf sämtliche Themen erstreckt. Viel mehr kann ist von partiespezifischen Themenschwerpunkten auszugehen.

> *H1: Die Parteien weisen bei den kleinen Anfragen Themenschwerpunkte vor, welche sich zwischen den Parteien unterscheiden.*

\newpage 

Anhand dieser Hypothese soll ermittelt werden, ob sich in der parlamentarischen Arbeit thematischen Präferenzen von Parteien erkennen lassen. Diese Frage könnte in der Parteienforschung interessant werden, um zu ermitteln, inwiefern eine Partei thematische Schwerpunkte im Wahlprogramm setzt, um Wahlen zu gewinnen oder ob die Partei inhärent den Drang besitzt, ein Thema im politischen System zu bedienen. Durch Anfragen im Bundestag können Oppositionsparteien stetig Informationen aus den Regierungsfraktionen erhalten, welche letztendlich in kommenden Wahlkämpfen instrumentalisierbar sind. 

Das Instrument der kleinen Anfragen wird im Bundestag hauptsächlich nur von Oppositionsparteien genutzt. Im 18. Bundestag befanden sich nur die Parteien Bündnis 90/Die Grünen und Die Linke in der Opposition. In der Regierung waren die Parteien SPD und CDU/CSU vertreten. Im 19. Bundestag blieb die Regierungskonstellation gleich, wohingegen zu den bestehenden Oppositionsparteien die Parteien AfD und FDP hinzu kamen. Nach der *Issue Ownership* sollten mit den neuen Parteien ebenso neue Themen im 19. Bundestag vertreten sein. Ausgehend dessen und der potentiellen Dominanz beider Parteien in spezifischen Themengebieten, kann vermutet werden, dass die bisher vertretenen Oppositionsparteien sich auf diese neu hinzugekommenen Themen verstärkt fokussieren.

> *H2: Die Themenschwerpunkte der Parteien Die Linke und Bündnis 90/Die Grünen haben sich im 19. Bundestag in Richtung der dominanten Themen der FDP und AFD verschoben.*

Eine letzte zu untersuchende Frage besteht darin, ob sich die Ansichten von Parteien aus unterschiedlichen politischen Richtungen bezüglich der selben Themen unterscheiden. Ausgehend von @geys2012success können mehrere Parteien ein Thema dominieren, jedoch können dabei unterschiedliche Ansichten vertreten sein. Bei einer deutlichen Differenz sollte dies durch das Sentiment beider Parteien deutlich werden.

> *H3: Parteien weisen bei den kleinen Anfragen zu gleichen Themen unterschiedliche Sentiments auf.*

### Aktueller Forschungsstand

Die Theorie der *Issue Ownership* ist eine relativ neue Herangehensweise, um das Wahlverhalten in politischen Systemen zu analysieren. Hierbei wird relativ schnell erkennbar, dass die Forschung aus theoretischer Sicht stagniert. In den meisten Studien werden nur empirische Überprüfungen getätigt. Eine tiefergehende Betrachtung der Theorie und Modifizierungen dieser findet kaum statt. Die Theorie von Budge & Farlie und Petrocik bleibt dementsprechend die Grundlage für alle zukünftigen Forschungen. Nur die Autoren Walgrave et al. versuchten sich an einer Modifizierung der Theorie und führten erste empirische Überprüfungen durch [@walgrave2012associative]. Benny Geys entwickelte ebenfalls einen theoretischen Ansatz, versuchte jedoch nicht seine Annahmen in einer empirischen Studie zu überprüfen [@geys2012success]. 

In der empirischen Anwendung wurden im Gegenzug bereits diverse Studien durchgeführt, um die Theorie der *Issue Ownership* zu überprüfen. Hierbei haben Forscher verschiedene Elemente und Schnittstellen der Theorie überprüft. In einer früheren Studie versuchten beispielsweise die Autoren Ansolabehere und Iyengar herauszufinden, ob für Wahlkampferfolge die *Issue Ownership* Theorie oder die *Riding the wave* Theorie bessere Erklärungen erzielen [@ansolabehere1994riding]. Kleinnijenhuis stellte ebenfalls einen Theorievergleich mit den Theorien *Issue Ownership*, *Issue convergence* und *Spatial Proximity* an [@kleinnijenhuisissue]. Im Gegenzug stellte sich Van Camp die Frage, inwiefern *Issue Ownership* eine Determinante für Medienberichterstattung ist und Walgrave und De Swert untersuchten, ob *Issue Ownership* von den Parteien oder den Medien stammt [@van2018issue; @walgrave2007does]. Gunther et al. versuchten zu evaluieren, wie stark BewerberInnen und deren Themen überhaupt in den Medien sichtbar sind [@gunther2017mediale]. Ein großer Teil der Forschung bezieht sich jedoch letztlich auf Parteien und wie *Issue Ownership* sich auf Wahlkampfstrategien, Parteienwettbewerb, Wahlkampfthemen und Parteipräferenzen auswirkt [@holian2004he; @green2008owning; @green2007growing; @stubager2013sources; @stubager2016can; @walgrave2014limits; @petrocik2003issue]. Die meiste Forschung wurde jedoch auf der Ebene der Wähler getätigt. Hierbei sollte untersucht werden, wie Faktoren wie Wissen, Wahldebatten, Themensalienz und Wahrnehmung einen Einfluss auf das Wahlverhalten oder auf Faktoren der *Issue Ownership* besitzen und wie dies gemessen werden kann [@belanger2008issue; @dejaeghere2017importance; @kaufmann2004disaggregating; @neundorf2018micro; @stubager2017issue; @van2004issue]. 

Äußerst aufschlussreiche  Studien wurden von Bélanger und Christensen et al. veröffentlicht. Bélanger untersuchte die Dynamiken innerhalb des *Issue Ownership* Konzepts und Christensen et al. untersuchten Änderungen von *Issue Ownership* innerhalb eines politischen Systems [@belanger2003issue; @christensen2015changes]. Alle Studien behandeln jedoch vordergründig westliche politische Systeme. Hierunter fallen die Vereinigten Staaten von Amerika, sowie Kanada, Schweden, Niederlande, Großbritannien, Deutschland, Dänemark und Belgien.
