---
output: pdf_document
---

Zusammenfassend konnte sich zeigen, dass die Parteien alle Themenschwerpunkte aufweisen. Auch wenn dabei teilweise Überschneidungen der Themenschwerpunkte vorliegt, kann eine gewisse Differenz zwischen den Oppositionsparteien festgestellt werden. Diese fallen dabei jedoch geringer aus als vermutet. Dennoch kann der erste Teil der Forschungsfrage positiv beantwortet werden. Ein hingegen unerwartetes Ergebnis ist der nicht vorhandene Einfluss der neu eingezogenen Parteien AfD und FDP auf die Themenschwerpunkte der Grünen und Linken. Trotz der teilweisen Unterschiede der Themenschwerpunkte der AfD und FDP zu den bisherigen Oppsitionsparteien, haben sich die Schwerpunkte der Grünen und Linken kaum verändert. Dies kann einerseits an der nicht vorhandenen Aussprache der Anfragen liegen, wodurch ein Einfluss dieser auf andere Parteien kaum vorhanden ist. Andererseits waren die Linken und Grünen bereits vor dem Einzug der AfD und FDP bei deren Themenschwerpunkten vertreten, wodurch hier eventuell kein Handlungsbedarf gesehen wurde um die Dominanz der anderen Parteien bei gewissen Themen zu mindern. Der zweite Teil der Forschungsfrage kann folglich negativ beantwortet werden, nach dem Einzug der AfD und FDP haben sich keine Veränderungen bei Grünen und Linken aufgezeigt.

Hinsichtlich der Sentiments konnte eine Heterogenität der Sentiments festgestellt werden. So unterscheidet sich das Sentiment zwischen den Parteien oftmals signifikant, auch wenn dies zwischen den Parteien nicht konsistent der Fall ist. Dennoch gibt es hierbei ein Problem mit der Fallzahl bei manchen Themen und Parteien, wodurch die Ergebnisse als weniger stabil angesehen werden müssen. Hinzu kommt die mangelnde Differenzierung der Unterthemen. So kann zwar ein ähnliches Sentiment vorliegen, jedoch können sich die Anfragen auf völlig unterschiedliche Aspekte beziehen. Dies wird durch die hier durchgeführte Analyse leider nicht berücksichtigt, wobei eine solche Berüksichtigung schweirig umzusetzen wäre.

Generell muss in Anbetracht der Analyse in Frage gestellt werden, ob die kleinen Anfragen eine adäquate Datengrundlage für die aufgestellte Forschungsfrage und den damit einhergehenden Hypothesen darstellt. Es ist zwar durchaus nachvollziehbar, dass Parteien die kleinen Anfragen gerade bei Themen nutzen, mit denen sie sich verstärkt auseinandersetzen. Mittels einer Auswertung der Worthäufigkeiten der einzelnen Parteiprogramme (siehe Abbildung \ref{word_freq}) kann sich lediglich bei der AfD eine tendenzielle Überschneidung der Themenschwerpunkte erkennen lassen. So kommen im Parteiprogramm der AfD häufig Wörter wie *Integration*, *Einwanderung*, *Kultur*, *Sprache* vor. Bei den anderen Parteien lassen sich durch die Worthäufigkeitsanalyse die hier identifizierten Themenschwerpunkte jedoch nicht vergleichbar wiedererkennen. Dabei sei jedoch anzumerken, dass die Worthäufigkeitsanalyse nicht ausreichend ist um mögliche Differenzen zwischen den Themenschwerpunkten in den Parteiprogrammen und den identifizierten Themenschwerpunkten anhand der kleinen Anfragen zu ermitteln. Dennoch lässt sich hierdurch eine mögliche Differenz erkennen, welche in künfitgen Arbeiten analysiert werden könnte. Ebenso fehlt bei den kleinen Anfragen die Aussprache in Form einer parlamentarischen Debatte, wodurch eine Einflussnahme auf andere Parteien nur bedingt möglich erscheint. Jedoch kann ein Wirkungsmechanismus zwischen den kleinen Anfragen und der parlamentarischen Agenda. Für eine Analyse eines solchen Wirkungsmechanismus müsste ein größerer Zeitraum mit mehr Daten betrachtet werden.

In Hinblick auf die Sentiments der einzelnen Parteien ist die Verwendung kleiner Anfragen womöglich nicht das beste Mittel. Einerseits findet bei den kleinen Anfragen keine Aussprache statt, wodurch diese tendenziell neutraler erscheinen, da es sich hierbei mehr um eine Informationsbeschaffung handelt. Andererseits ist die Vergleichbarkeit nur bedingt gegeben. Die Anfragen wurden zwar nach Themen des *Comparative Agendas Project* kodiert, jedoch gibt es bei den einzelnen Thmen nochmals weitere Differenzierungsmöglichkeiten. Die Verwendung von parlamentarischen Reden der einzelnen Parteien zu den selben Themen erscheint dabei folglich als das adäquatere Mittel. Die Themen, welche auf das *Comparative Agendas Project* zurückzuführen sind, könnten folglich ebenso dazu dienen um die parlamentarischen Tagesordnungen zu kategorisieren und die Reden der einzelnen Parteimitglieder zu analysieren. Auf diese Weise ist eine bedeutend bessere Vergleichbarkeit gegeben als bei den kleinen Anfragen, wo das konkrete Thema, zu welchem die Anfrage gestellt wird, von der Fraktion selbst vorgegeben wird. Eine solche Analyse kann auch mit der hier getätigten Analye der kleinen Anfragen kombiniert werden.

